allowed-duplicate-crates = [
    "axum",
    "axum-core",
    "base64",
    "bitflags",
    "fallible-iterator",
    "foreign-types",
    "foreign-types-shared",
    "getrandom",
    "hashbrown",
    "indexmap",
    "itertools",
    "linux-raw-sys",
    "matchit",
    "rand",
    "rand_chacha",
    "rand_core",
    "regex-automata",
    "regex-syntax",
    "rustix",
    "syn",
    "thiserror",
    "thiserror-impl",
    "tower",
    "wasi",
    "webpki-roots",
    "windows-strings",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
]